### ISSUE TITLE
no version on some modules

### ISSUE THREAD

**Issue by Mithgol** [rvagg/nodei.co#29]
Currently even on the main page of https://nodei.co/ some modules' versions are not displayed, `through2` and `moment` and `bole` and `esctatic` and `async` for example.

**Comment by PeterDaveHello** [comment]
I can see async v1.4.0
![https://nodei.co/npm/async.png](https://nodei.co/npm/async.png)

**Comment by rvagg** [comment]
might have been a momentary blip, there is a separate service that collects and serves "package info" to the main service that does the rendering, it's set up so that the images can still be rendered even if it doesn't manage to get the full package info so perhaps it died and was automatically restarted

**Comment by Mithgol** [comment]
Ok.
