### ISSUE TITLE
502 Error

### ISSUE THREAD

**Issue by Richienb** [rvagg/nodei.co#47]
The server is responding with 502 Bad Gateway.

I recommend switching to a serverless platform like Vercel to mitigate these issues.

// @rvagg

**Comment by rvagg** [comment]
The problem here is the logs keep on blowing out my storage needs, and the logs grow fast because it generates internal errors on each request because it still tries to fetch from the download service (internal call) which is disabled because npm made all that harder...  The solution is to fix the extraneous logs and implement better log rotation, but those things take time, so it's another thing on my TODO list.
